services:
  - type: redis
    name: blabhear-redis
    region: ohio
    plan: free
    ipAllowList: [] # only allow internal connections

  - type: web
    name: blabhear-backend
    env: python
    repo: https://github.com/KnowYourLines/blabhear-backend.git
    region: ohio
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt; python manage.py makemigrations blabhear; python manage.py migrate; python manage.py collectstatic --no-input"
    startCommand: "daphne server.asgi:application --bind 0.0.0.0 --port $PORT"
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: blabhear-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: blabhear-redis
          property: connectionString
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_CLIENT_CERT_URL
        sync: false

databases:
  - name: blabhear-db
    plan: free
    region: ohio
    postgresMajorVersion: 14
    ipAllowList: [] # only allow internal connections
