# Generated by Django 3.2.18 on 2023-04-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alpha2_country_code',
            field=models.CharField(default='GB', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=150),
        ),
    ]
