# Generated by Django 3.2.18 on 2023-04-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0002_auto_20230419_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='Johnny', max_length=150),
            preserve_default=False,
        ),
    ]
