# Generated by Django 3.2.18 on 2023-07-15 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0007_auto_20230709_1657'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userroomnotification',
            name='unique_notification',
        ),
        migrations.AddField(
            model_name='userroomnotification',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blabhear.message'),
        ),
        migrations.AddField(
            model_name='userroomnotification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='userroomnotification',
            constraint=models.UniqueConstraint(fields=('room', 'user', 'message'), name='unique_notification'),
        ),
    ]
