# Generated by Django 3.2.18 on 2023-07-15 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0008_auto_20230715_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='userroomnotification',
            name='unique_notification',
        ),
        migrations.AddConstraint(
            model_name='userroomnotification',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='unique_notification'),
        ),
        migrations.AddField(
            model_name='messagenotification',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blabhear.message'),
        ),
        migrations.AddField(
            model_name='messagenotification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagenotification',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blabhear.room'),
        ),
        migrations.AddConstraint(
            model_name='messagenotification',
            constraint=models.UniqueConstraint(fields=('room', 'receiver', 'message'), name='unique_msg_notification'),
        ),
    ]
