# Generated by Django 3.2.18 on 2023-07-18 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0012_report_message_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='message_uuid',
        ),
        migrations.AddField(
            model_name='report',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blabhear.message'),
            preserve_default=False,
        ),
    ]
