# Generated by Django 3.2.18 on 2023-07-18 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0013_auto_20230718_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='message',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='blabhear.message'),
        ),
    ]
