# Generated by Django 3.2.18 on 2023-08-14 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0014_alter_report_message'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='unique_creator_room_message',
        ),
    ]
