# Generated by Django 3.2.18 on 2023-09-06 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0015_remove_message_unique_creator_room_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagenotification',
            name='read',
        ),
    ]
