# Generated by Django 3.2.18 on 2023-10-09 03:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabhear', '0017_user_blocked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='_blabhear_user_blocked_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
